package ir.samta.project.domain.enumeration;

/**
 * The FinancialProjectType enumeration.
 */
public enum FinancialProjectType {
    CREDIT_ESTIMATES,
    SELL_CONTRACT_AMOUNT,
    AMOUNT_CONFIRMED,
    RECEIVED_FROM_INSTITUTION,
    RECEIVED_FROM_ORGANIZATION,
    RECEIVED_TOTAL_FOR_PROJECT,
    SEND_TO_PROJECT_HAVE_CODE,
    SEND_TO_PROJECT_NOT_HAVE_CODE,
    SURPLUS_COST,
    CREDIT_REMAIN,
    BEFORE_CLEARING,
    IN_CLEARING,
    FINAL_CLEARING,
    DEBIT_TO_INSTITUTION,
    CREDIT_APPLY,
    SEND_TO_OTHER_PROJECT,
    RECEIVED_FROM_OTHER_PROJECT
}
